config/routes.rb
Rails.application.routes.draw do
   scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do

 
 
 devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'pages#index', as: :authenticated_root
  end
  root "devise/sessions#new"
end
  
  
  resources:payments
  resources :reserves
  resources :clients
  resources :expends
  resources :rooms
  resources :bills do 
     resources :bill_details
   end
  resources :room_types
  resources :users
  
  resources :hotels
  get '/contact', to: 'pages#contact'
  
  get '/index', to: 'pages#index'

end
end

app/models/bill_detail.rb
class BillDetail < ActiveRecord::Base
  belongs_to :expend
  belongs_to :bill
  
  
  validates_presence_of :expend
  validates_presence_of :bill
  
  accepts_nested_attributes_for :expend
  
  
  def sub_total
  expend.monto * cantidad 
  end
  
end

app/controllers/bill_details_controller.rb
class BillDetailsController <ApplicationController
  before_action :authenticate_user!                                                                 
  before_action :set_bill_detail, only: [:show, :edit, :update, :destroy]

  # GET /bill_details
  # GET /bill_details.json
  def index
    @bill_details = BillDetail.all
  end

  # GET /bill_details/1
  # GET /bill_details/1.json
  def show
  end

  # GET /bill_details/new
  def new
    @bill=Bill.find(params[:bill_id])
    @bill_detail = BillDetail.new
  end

  # GET /bill_details/1/edit
  def edit
    @bill = bill.find(params[:bill_id]);
   @bill_detail = bill_detail.find(params[:id]);
   @cantidad = @bill_detail.cantidad;
  end

  # POST /bill_details
  # POST /bill_details.json
  def create
    @bill.Bill.find(params[:bill_id])
    @bill_detail = @bill.BillDetails.new(bill_detail_params)
    redirect_to bill_patch(@bill)

    respond_to do |format|
      if @bill_detail.save
        format.html { redirect_to @bill, notice: 'Bill detail was successfully created.' }
        format.json { render :show, status: :created, location: @bill_detail }
      else
        format.html { render :new }
        format.json { render json: @bill_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_details/1
  # PATCH/PUT /bill_details/1.json
  def update
    @bill.Bill.find(params[:bill_id])
    @bill_detail = Bill_detail.find(params[:id]);
   @bill_detail.cantidad = @cantidad;

    respond_to do |format|
      if @bill_detail.update(bill_detail_params)
        format.html { redirect_to @bill, notice: 'Bill detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_detail }
      else
        format.html { render :edit }
        format.json { render json: @bill_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_details/1
  # DELETE /bill_details/1.json
  def destroy
    @bill.Bill.find(params[:bill_id])
    @bill_detail = Bill_detail.find(params[:id]);
    if @bill_detail.destroy
    respond_to do |format|
      format.html { redirect_to @bill, notice: 'Bill detail was successfully destroyed.' }
      format.json { head :no_content }
       end
    else
      redirect_to @bill, :notice => "El comentario no se ha podido eliminar";
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_detail
      @bill_detail = BillDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_detail_params
      params.require(:bill_detail).permit(:expend_id, :bill_id, :cantidad)
    end
end

app/helpers/bill_details_helper.rb
module BillDetailsHelper
end

app/views/bill_details/_form.html.erb
<%= form_for(@bill_detail) do |f| %>
  <% if @bill_detail.errors.any? %>
    
        <div id="error_explanation">
      <h2><%= pluralize(@bill_detail.errors.count, "errores") %>  no permiten se guarde  bill_detail  </h2> 

      <ul>
      <% @bill_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expend_id %><br>
    <%= f.text_field :expend_id %>
  </div>
  <div class="field">
    <%= f.label :bill_id %><br>
    <%= f.text_field :bill_id %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_details/edit.html.erb
<h1>Editing Bill Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_detail %> |
<%= link_to 'Back', bill_details_path %>

app/views/bill_details/index.html.erb
<h1>Listing Bill Details</h1>

<table>
  <thead>
    <tr>
      <th>Expend</th>
      <th>Bill</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_details.each do |bill_detail| %>
      <tr>
        <td><%= bill_detail.expend %></td>
        <td><%= bill_detail.bill %></td>
        <td><%= bill_detail.cantidad %></td>
        <td><%= link_to 'Show', bill_detail %></td>
        <td><%= link_to 'Edit', edit_bill_detail_path(bill_detail) %></td>
        <td><%= link_to 'Destroy', bill_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill detail', new_bill_bill_detail_path %>

app/views/bill_details/new.html.erb
<h1>New Bill Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_bill_details_path %>

app/views/bill_details/show.html.erb
<p>
  <strong>Expend:</strong>
  <%= @bill_detail.expend %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @bill_detail.bill %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @bill_detail.cantidad %>
</p>

<%= link_to 'Edit', edit_bill_detail_path(@bill_detail) %> |
<%= link_to 'Back', bill_details_path %>