config/routes.rb
Rails.application.routes.draw do
   scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do

 
 
 devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'pages#index', as: :authenticated_root
  end
  root "devise/sessions#new"
end
  
  
  resources:payments
  resources :reserves
  resources :clients
  resources :expends
  resources :rooms
  resources :bills do 
     resources :bill_details
   end
  resources :room_types
  resources :users
  
  resources :hotels
  get '/contact', to: 'pages#contact'
  
  get '/index', to: 'pages#index'

end
end

app/models/bill.rb
class Bill < ActiveRecord::Base
 include Filterable
  belongs_to :client
  belongs_to :reserve
  
  has_many :bill_details, :dependent => :destroy
  has_many :expends, :through => :bill_details
  
  before_save :set_cod, :total_price

  accepts_nested_attributes_for :bill_details , allow_destroy: true, 
  reject_if: proc { |attr| attr[].blank? }
  
  validates :monto_total, presence: true , numericality: true
  validates :client_id, :reserve_id, presence: true
  
  
  def subtotal
   self.bill_details.cantidad * expend.monto 
  end
  
private

  def total_price
    @total_price ||= bill_details.includes(:expend).reduce(0) do |sum, b_det|
      sum + (b_det.cantidad * b_det.expend.monto)
    end
  end
  
  def set_cod
    self.codigo =  "f4004" + self.id.to_s 
  end

  def montototal
    self.monto_total = bill_details.collect { bill_details.cantidad * expend.monto }.sum
  end
  
  def total
  self.expends.sum(:price)
  end
end
     

app/controllers/bills_controller.rb
class BillsController <ApplicationController
  before_filter :authenticate_user!
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
 

  # GET /bills
  # GET /bills.json
  def index
   @bills = Bill.all 
   @bill_details =BillDetail.all
   @reserve=Reserve.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
   @bill = Bill.find(params[:id])
   @client= Client.all
     @reserve=Reserve.all
     @details=BillDetail.all
     @expends=Expend.all
   respond_to do |format|
      format.html
      format.pdf { render :pdf => generate_pdf(@bill) }
    end
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    @client = Client.where(cedula: @bill.client_id).last
    @bill.codigo= "0000205"+""+@bill.id.to_s 
    @clients= Client.all
    @reserves=Reserve.all
   # @bill_details=
    @bill.bill_details.build#.build_expend
    #@bill.expends.build
  #  @expends=@bill_details.expend.build
     if params[:search]
          @search = Client.search(params[:search])
     end
  end

  # GET /bills/1/edit
  def edit
     @bill = Bill.find(params[:id])
    @client= Client.all
     @reserve=Reserve.all
     @details=BillDetail.all
     @expends=Expend.all
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
   # @client = Client.find(@bill.client_id)
    #@reserf= Reserve.find(@bill.reserve_id)
    
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Factura  registrada exitosamente.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Factura actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Factura eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:id, :client_id, :reserve_id,:monto_total,:codigo,:tipo_pago, 
      bill_detail_attributes: [:id, :cantidad, 
      expend_attributes:[:id, :descripcion] ])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill_detail_fields.erb
<tr class="nested-fields">
  
  <% f.object.build_expend if f.object.new_record?%>
  <%= f.simple_fields_for :expends, wrapper: false do |exp_form|%>
  
  <td class="col-md-3"><%= f.association :expend , label_method: :descripcion, value_method: :id, prompt:"Seleccione" , wrapper: false, label: false %></td>
  <td class="col-xs-3"><%= exp_form.input :monto, label: false  %></td>
  <td class="col-xs-3"><%=f.input :cantidad , label: false  %></td>
  <td class="col-xs-3"><%= f.input :cantidad,  label: false  %></td>
  <td class="col-xs-3"><%= link_to_remove_association "Eliminar consumo",f, wrapper: false ,label: false%></td>
   <%# <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> remove 
  </td>
 <% end %>
  <% end %>
</tr>

  
 

app/views/bills/_form.html.erb
<%= simple_form_for(@bill, html: { class: 'form-horizontal' }) do |f| %>
  
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "errores") %>  no permiten se guarde  la factura </h2> 

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   <h3>Factura nº <%=f. input_field :codigo , disabled: true%></h3>

  
 
  <%= f.association :client ,:label => "Cliente", label_method: :nombre, value_method: :id, prompt:"Seleccione" %>
  <%= f.association :reserve,:label => "Reserva", label_method: :fecha_fin, value_method: :id, prompt:"Seleccione"%>
  <%= f.input :tipo_pago ,collection: ["Debito" ,"Credito", "Efectivo"], prompt:"Seleccione"%>
   
    <div class="row lista">
      
      
    <table class=" table table-bordered" >
       
    <thead >
     
    <tr>
      <th class="col-xs-3">Consumo</th>
      <th class="col-xs-3">Precio</th>
      <th class="col-xs-3">Cantidad</th>
      <th class="col-xs-3">SubTotal</th>
      <th class="col-xs-3"></th>
      
    </tr>
  </thead>
 
  <tbody id='billd_table'>
    
  
    </tbody>
    <%= f.simple_fields_for :bill_details do |billd_form|%>
       
   <tr><%= link_to_add_association 'agregar consumo', f, :bill_details, data: {:'association-insertion-traversal' => 'in',:'data-association-insertion-node' => 'tbody#billd_table', :'association-insertion-method' => :append}%></tr> 

   
  </table >
  
       
    <% end %>
  </div>
   
  <%= f.input :monto_total , values:  @total_price  %>
    
    <h1> <%= @total_price %> </h1> 


  <div class="actions col-md-6" align="center">
       <%= link_to 'Atras', bills_path, :class=>"btn btn-fcv"  %>
       <%= f.submit 'Guardar', class: "btn btn-fcv"%>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Modificar Factura</h1>

<%= render 'form' %>

app/views/bills/index.html.erb
  </br>
  <div class="walllogin container"></br>
  <div class="row">
      <div class="imagen_logo">
          
      </div>
  </div></br></br>
  <div class="row"><h2 align="center">LISTADO DE FACTURAS</h2></div></br>
  <div class="row">
    <div class="col-md-2 col-md-offset-1">
       <%= link_to new_bill_path, { :class => "btn btn-fcv"} do %>
            <i class="fa fa-fw fa-plus"></i> Registrar Factura
       <% end %>
    </div>
    <div class="col-md-3 col-md-offset-6">
      
      <div class="col-offset-08" >
        <%= form_tag(bills_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Codigo " %>
        <%= submit_tag "Buscar" , :class => "btn-fcm"%>
        <% end %>
       <% if @bills.present? %>        
      </div>
    </div>
  </div></br>
  <div class="row lista">
    <table class=" table table-bordered" >
    <thead>
    <tr>
      <th>Codigo</th>
      <th>Cliente</th>
      <th>Fecha entrada de reserva</th>
      <th>Monto Total</th>
      <th colspan="3">Opciones</th>
      </tr>
    </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.codigo %></td>
         <td><%= bill.client.nombre%></td>
          <td><%= bill.reserve.fecha_init %></td>
          <td><%= bill.monto_total %></td>
        <td><%= link_to 'Mostrar', bill, {:class => "btn-xs btn-fcv" } %></td>
          <td><%= link_to 'Editar', edit_bill_path(bill), {:class => "btn-xs btn-fcv" } %></td>
          <% if current_user.rol=="gerente" %>
          <td><%= link_to 'Eliminar', bill,  method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
          <%end%>
        </tr>
      <% end %>
   <% else %>
  <div class="row"><h2 align="center">No hay facturas  <%= params[:search] %></h1>
    </tbody>
  </table>
  </div>
</body>
<% end %>

app/views/bills/new.html.erb
<h1>Registrar Factura</h1>

<%= render 'form' %>

app/views/bills/show.html.erb
<div class="wrapper">
    <div class="col-s-4 col-md-offset-4" >
     <%= image_tag "Captura.jpg", class: "watermark" %>
   </div> 

   <div class="col-md-5" align="left">

<p>
  <h2>Cliente: <%= @bill.client.nombre %></h2>
  
</p>

<p>
  <strong>Fecha:</strong>
  <%= @bill.created_at%>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @bill.codigo %>
</p>

<p>
  <strong>Fecha Entrada reservacion:</strong>
  <%= @bill.reserve.fecha_init %>
</p>

<p>
  <strong>Fecha salida reservacion:</strong>
  <%= @bill.reserve.fecha_fin %>
</p>


<p>
  <strong>Monto Total:</strong>
  <%= @bill.monto_total %>
</p>


<%= link_to 'Atras', bills_path %>
</div></div>