config/routes.rb
Rails.application.routes.draw do
   scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do

 
 
 devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'pages#index', as: :authenticated_root
  end
  root "devise/sessions#new"
end
  
  
  resources:payments
  resources :reserves
  resources :clients
  resources :expends
  resources :rooms
  resources :bills do 
     resources :bill_details
   end
  resources :room_types
  resources :users
  
  resources :hotels
  get '/contact', to: 'pages#contact'
  
  get '/index', to: 'pages#index'

end
end

app/models/room.rb
class Room < ActiveRecord::Base
    include Filterable
    belongs_to :room_type
    has_many :reserves
    belongs_to :hotel
    
    
    validates :estatus,:piso, :cod_hab ,presence: true
    validates :cod_hab , uniqueness: true
    validates :piso, numericality: { only_integer: true }
    
    
    accepts_nested_attributes_for :room_type , reject_if: proc { |attr| attr[].blank? }
  
  
  def asig_cod_hab
    self[:cod_hab] = self.id
  end

  
  def self.search(search)
  where("estatus LIKE ?", "%#{search}%") 
  end
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
   
    has_many :rooms
    validates :desc_th,:precio, presence: true
    validates :precio, numericality:{ :greater_than => 0}
    
    def mayus(desc_th)
    self.desc_th.capitalize

    end

end

app/controllers/rooms_controller.rb
class RoomsController <ApplicationController
  before_action :authenticate_user!                                                                 
  before_action :set_room, only: [:show, :edit, :update, :destroy]
   

  # GET /rooms
  # GET /rooms.json
  def index
    @RoomTypes = RoomType.all
    if params[:search]
    @rooms = Room.search(params[:search]).order("created_at DESC")
   else
    @rooms = Room.all.order('created_at DESC')
    end
    
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
     @RoomTypes = RoomType.all
  end

  # GET /rooms/new
  def new
    @room = Room.new
    @RoomTypes = RoomType.all
  end

  # GET /rooms/1/edit
  def edit
    @room=Room.find(params[:id])
    @RoomTypes = RoomType.all
  end

  # POST /rooms
  # POST /rooms.json
  def create
  
   @room = Room.new(room_params)
   @RoomType= RoomType.find(@room.room_type_id )
      
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Habitacion registrada exitosamente.'}
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        unless index 
        format.html { redirect_to @room, notice: 'Habitacion actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Habitacion eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:cod_hab, :piso, :estatus,:room_type_id)
    end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "errores") %>  no permiten se guarde la habitacion</h2> 

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  
  <div class="col-md-6">
    <%= f.input :cod_hab,label:"nro Habitacion "  %>
   <%= f.association :room_type , label:"Tipo de Habitacion ", label_method: :desc_th, value_method: :id, prompt:"Seleccione" %>
   <%= f.input :piso ,collection: 1..20%>
   <%= f.input :estatus, collection: ["Disponible" ,"Reservada", "Fuera de Servicio","En servicio"], prompt:"Seleccione", :class =>"form-control" %>
  
  <div class="actions" align="center">
    <%= f.submit 'Guardar', class: "btn btn-fcv"%>
    <%= link_to 'Atras', rooms_path, :class=>"btn btn-fcv"  %>
  </div>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editar Habitacion</h1>

<%= render 'form' %>

app/views/rooms/index.html.erb
  </br>
  <div class="row">
  </div></br></br>
 <div class="row"><h2 align="center">LISTADO DE HABITACIONES</h2></div></br>
  <div class="form-inline">
    
       <%= link_to new_room_path, { :class => "btn btn-fcv"} do %>
            <i class="fa fa-fw fa-plus"></i> Registrar Habitacion
       <% end %>
    
       <%= link_to room_types_path, { :class => "btn btn-fcv"} do %>
            <i class="fa fa-fw fa-plus"></i>  Tipos de Habitacion
       <% end %>
       
      <div class="col-offset-08" >
        <%= form_tag(rooms_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Estado Habitacion" %>
        <%= submit_tag "Buscar" , :class => "btn-fcm"%>
        <% end %>
       <% if @rooms.present? %>
      </div>
  </div></br>
  <div class="row lista">
    <table class=" table table-bordered" >
    <thead>
      <tr>
      <th>Nro Hab</th>
      <th>Piso</th>
      <th>Estatus</th>
      <th>Descripcion</th>
      <th colspan="3 align:center">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.cod_hab%></td>
        <td><%= room.piso %></td>
        <td><%= room.estatus %></td>
        <td><%= room.room_type.desc_th %> </td>
       <td><%= link_to 'Mostrar', room, {:class => "btn-xs btn-fcv" } %></td>
          <td><%= link_to 'Editar', edit_room_path(room), {:class => "btn-xs btn-fcv" } %></td>
          <td><%= link_to 'Eliminar', room,  method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
        </tr>
<%end %>   
       

    </tbody>
  </table>
   <% else %>
  <div class="row"><h2 align="center">No hay habitaciones  <%= params[:search] %></h1>
  </div>
</body>
<% end %>

app/views/rooms/new.html.erb
<h1>Registrar Habitacion</h1>

<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="wrapper">
    <div class="col-s-4 col-md-offset-4" >
     <%= image_tag "Captura.jpg", class: "watermark" %>
   </div> 

  <div class="col-md-5" align="left">


<h1><%= @room.room_type.desc_th %><h1>
<br>
<p>
  <strong>Piso:</strong>
  <%= @room.piso %>
</p>

<p>
  <strong>numero habitacion:</strong>
  <%= @room.cod_hab %>
</p>
<p>
  <strong>Estatus:</strong>
  <%= @room.estatus %>
</p>
<div class="actions col-md" align="center " >
<%= link_to 'Editar', edit_room_path(@room) ,class:"btn btn-fcv" %> 
<%= link_to 'Atras', rooms_path, class:"btn btn-fcv"  %>

</div>
</div>
</div>