config/routes.rb
Rails.application.routes.draw do
   scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do

 
 
 devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'pages#index', as: :authenticated_root
  end
  root "devise/sessions#new"
end
  
  
  resources:payments
  resources :reserves
  resources :clients
  resources :expends
  resources :rooms
  resources :bills do 
     resources :bill_details
   end
  resources :room_types
  resources :users
  
  resources :hotels
  get '/contact', to: 'pages#contact'
  
  get '/index', to: 'pages#index'

end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
      if user.rol == "gerente"
        can :manage, :all
       else
        cannot :manage,User,Hotel 
        cannot :destroy, Bill
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/bill.rb
class Bill < ActiveRecord::Base
 include Filterable
  belongs_to :client
  belongs_to :reserve
  
  has_many :bill_details, :dependent => :destroy
  has_many :expends, :through => :bill_details
  
  before_save :set_cod, :total_price

  accepts_nested_attributes_for :bill_details , allow_destroy: true, 
  reject_if: proc { |attr| attr[].blank? }
  
  validates :monto_total, presence: true , numericality: true
  validates :client_id, :reserve_id, presence: true
  
  
  def subtotal
   self.bill_details.cantidad * expend.monto 
  end
  
private

  def total_price
    @total_price ||= bill_details.includes(:expend).reduce(0) do |sum, b_det|
      sum + (b_det.cantidad * b_det.expend.monto)
    end
  end
  
  def set_cod
    self.codigo =  "f4004" + self.id.to_s 
  end

  def montototal
    self.monto_total = bill_details.collect { bill_details.cantidad * expend.monto }.sum
  end
  
  def total
  self.expends.sum(:price)
  end
end
     

app/models/bill_detail.rb
class BillDetail < ActiveRecord::Base
  belongs_to :expend
  belongs_to :bill
  
  
  validates_presence_of :expend
  validates_presence_of :bill
  
  accepts_nested_attributes_for :expend
  
  
  def sub_total
  expend.monto * cantidad 
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
 include Filterable
 has_many :reserves ,:dependent => :destroy
 validates  :cedula, uniqueness: true, presence: true
 validates  :telefono,  numericality: true, presence: true
 validates  :nombre, :apellido ,presence: true
 
 
 
  def self.search(search)
   
  where("apellido LIKE ?", "%#{search}%") 
  where("nombre LIKE ?", "%#{search}%") 
  
  end 
  
  def self.buscar(search)
   where("cedula LIKE ?", "%#{search}%") 
  end
end

app/models/expend.rb
class Expend < ActiveRecord::Base
   has_many :bill_details
   has_many :bills, :through => :bill_details
   
   validates :descripcion, :monto, presence: true 
   validates :monto ,numericality:{ :greater_than => 0}
   
   def self.search(search)
       where("descripcion LIKE ?", "%#{search}%") 
   end
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
 include Filterable
 has_many :rooms
 validates  :rif, uniqueness: true, presence: true
 validates  :rif, :telefono,  numericality: true, presence: true
 validates  :tipo, :nombre, presence: true
   
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
 include Filterable

  belongs_to :client
  has_one :room
  before_save :cal_monto

  validates :fecha_fin, :fecha_init, :estatus ,:client_id , :room_id , presence: true
  #validates  :monto, numericality: true, presence: true
  validates_date :fecha_init, :on_or_after => lambda { Date.current }, message: "Solo a partir del dia de hoy "
  validates_date :fecha_fin, :after => :fecha_init 
  
  accepts_nested_attributes_for :client, :room 
 
 def cal_monto
 
   self.monto * (self.fecha_fin - (self.fecha_init))
 end
 
   private
  
  def self.search(search)
  where("estatus LIKE ?", "%#{search}%") 
  end

  
   
  def active
     hoy=Time.now
    if hoy>= fecha_init and hoy <= fecha_fin
     else 
       self.estatus==vencida
    end
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
    include Filterable
    belongs_to :room_type
    has_many :reserves
    belongs_to :hotel
    
    
    validates :estatus,:piso, :cod_hab ,presence: true
    validates :cod_hab , uniqueness: true
    validates :piso, numericality: { only_integer: true }
    
    
    accepts_nested_attributes_for :room_type , reject_if: proc { |attr| attr[].blank? }
  
  
  def asig_cod_hab
    self[:cod_hab] = self.id
  end

  
  def self.search(search)
  where("estatus LIKE ?", "%#{search}%") 
  end
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
   
    has_many :rooms
    validates :desc_th,:precio, presence: true
    validates :precio, numericality:{ :greater_than => 0}
    
    def mayus(desc_th)
    self.desc_th.capitalize

    end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Filterable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true
  before_save :set_rol

  private
  def set_rol
    self.rol='administrador'if rol.nil?
  end

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/expends_helper.rb
module ExpendsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">


<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GHOTEL</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :cocoon %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  
  
  
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <%= csrf_meta_tags %>
 
 
</head>

<body>
  <div class="walllogin container"></br>    

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"    ;>
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <%= link_to root_path do %>
  <%= content_tag :span, "GHOTEL", :class => "navbar-brand", :remote => true %>
<% end %>
               
            </div>
          
            
 <% if user_signed_in? %>
  <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav"  width: 200px height: 200;>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="https://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong><%= current_user.email %></strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Ayer  4:32 PM</p>
                                        <p>Nueva Reserva</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <br></br>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="https://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong><%= current_user.email %></strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Ayer  4:32 PM</p>
                                        <p>Pago consumos</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="https://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong><%= current_user.email %></strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Ayer  4:32 PM</p>
                                        <p>Servicio Cancelado...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Leer nuevos mensajes</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Mensaje <span class="label label-default"></span></a>
                        </li>
                        <li>
                            <a href="#">Mensaje <span class="label label-primary"></span></a>
                        </li>
                        <li>
                            <a href="#">Mensaje <span class="label label-success"></span></a>
                        </li>
                        <li>
                            <a href="#">Mensaje <span class="label label-info"></span></a>
                        </li>
                        <li>
                            <a href="#">Mensaje <span class="label label-warning"></span></a>
                        </li>
                        <li>
                            <a href="#">Mensaje <span class="label label-danger"></span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">Ver Todos</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.name %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                        <a ><i class="fa fa-fw fa-user"></i> <%= link_to "Perfil", edit_user_registration_path %></a>
                          
                      </li>
                       <li>
                           <a href="#"><i class="fa fa-fw fa-envelope"></i>Actividades</a>
                       </li>
                       <li>
                           <a href="#"><i class="fa fa-fw fa-gear"></i> Configurar </a>
                       </li>
                       <li class="divider"></li>
                       <li>
                            <a class="fa fa-fw fa-power-off"> <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></a> 
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
 
 
<!-- Navigation  -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav" style=" width: 180px">
                    <li class="active">

            <li>
                <%= link_to "Inicio", root_path %>                    
            </li>
             <li>
                <%= link_to "Reservaciones", reserves_path %>
            </li>
             <li>
                <%= link_to "Habitaciones", rooms_path %>
            </li>
             <li>
                <%= link_to "Consumos", expends_path %>
            </li>
             <li>
                <%= link_to "Clientes", clients_path %>
            </li>
             <li>
                <%= link_to "Facturas", bills_path %>
            </li>
            <% if current_user.rol=="gerente" %>
             <li>
               <%= link_to "Hotel", hotel_path(3) %>
             </li>
            <li>
                <%= link_to "Usuarios", users_path %>
            </li>
            
               <% end %>    
            <li>
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %> 
            </li>
                        
        </ul>
    </nav>
 <% else %>
    <a id="menu-toggle" href="#" class="btn btn-fcm btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-md pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <a href="#top"  onclick = $("#menu-close").click(); >Menú de opciones</a>
            </li>
            <li>
                <%= link_to " Inicio", root_path %>                    
            </li>
             <li>
                <%= link_to " Contáctos", contact_path %>
            </li>
          
        </ul>
    </nav>
    <% end %>


            
            
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    

   

</body>
<div id=container style=" padding-left: 35px;
    margin-left: 140px;">
<div class="walllogin container"></br>
    

<p class="notice"> <%=notice%></p>
<p class="alert"> <%=alert%></p>
<%= yield %>


    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>

</body>
</div>

</div>
</html>